module.exports = {
  libraries: [
    {
      id: "jquery",
      name: "jQuery",
      src: "https://unpkg.com/jquery",
      docs: "https://api.jquery.com/",
      crossorigin: false,
    },
    {
      id: "lodash",
      name: "Lodash",
      src: "https://unpkg.com/lodash",
      docs: "https://lodash.com/docs/",
      crossorigin: false,
    },
    {
      id: "ramda",
      name: "Ramda",
      src: "https://unpkg.com/ramda",
      docs: "https://ramdajs.com/docs/",
      crossorigin: false,
    },
    {
      id: "handlebars",
      name: "Handlebars",
      src: "https://unpkg.com/handlebars@latest/dist/handlebars.js",
      docs: "https://handlebarsjs.com/guide/",
      crossorigin: false,
    },
    {
      id: "angularjs",
      name: "AngularJS",
      src: "https://unpkg.com/angular@latest/angular.js",
      docs: "https://docs.angularjs.org/api",
      crossorigin: false,
    },
    {
      id: "zepto",
      name: "ZeptoJS",
      src: "https://zeptojs.com/zepto.min.js",
      docs: "https://zeptojs.com/",
      crossorigin: false,
    },
    {
      id: "underscore",
      name: "UnderscoreJS",
      src: "https://underscorejs.org/underscore-min.js",
      docs: "https://underscorejs.org/",
      crossorigin: false,
    },
    {
      id: "backbone",
      name: "BackboneJS",
      src: "https://backbonejs.org/backbone-min.js",
      docs: "https://backbonejs.org/",
      crossorigin: false,
    },
    {
      id: "react",
      name: "ReactJS",
      src: "https://unpkg.com/react@latest/umd/react.development.js",
      docs: "https://reactjs.org/docs/getting-started.html",
      crossorigin: true,
    },
    {
      id: "vue",
      name: "Vue",
      src: "https://unpkg.com/vue@2",
      docs: "https://v2.vuejs.org/v2/guide/",
      crossorigin: false,
    },
    {
      id: "vue3",
      name: "Vue 3",
      src: "https://unpkg.com/vue@3",
      docs: "https://vuejs.org/guide/introduction.html",
      crossorigin: false,
    },
    {
      id: "rxjs",
      name: "RxJS",
      src: "https://unpkg.com/rxjs/dist/bundles/rxjs.umd.min.js",
      docs: "https://rxjs.dev/api",
      crossorigin: false,
    },
    {
        id: "mobxjs",
        name: "MobX",
        src: "https://unpkg.com/mobx/dist/mobx.umd.production.min.js",
        docs: "https://mobx.js.org/",
        crossorigin: false,
      }
  ],
};
